### ISSUE TITLE
Add Dynamic Ingress IP Configuration for Frontend

### ISSUE THREAD

**Issue by LavleshJ** [TheFirewall-code/TheFirewall-Secrets-SCA#9]
### Current Problem
Customers need to update `VITE_API_BASE_URL` with the Ingress IP address after deployment, but this information is only available after the Ingress is created.

### Solution
We'll modify the Helm chart to:
1. Add an initContainer to wait for and fetch the Ingress IP
2. Mount this information as an environment variable for the frontend container

### Required Changes

1. Add a ConfigMap template to store the Ingress IP:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thefirewall.fullname" . }}-ingress-config
data:
  # Will be updated by the init container
  INGRESS_IP: ""
```

2. Add ServiceAccount and Role for accessing Ingress information:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "thefirewall.fullname" . }}-ingress-reader
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "thefirewall.fullname" . }}-ingress-reader
subjects:
- kind: ServiceAccount
  name: {{ include "thefirewall.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "thefirewall.fullname" . }}-ingress-reader
  apiGroup: rbac.authorization.k8s.io
```

3. Update frontend deployment to include initContainer:
```yaml
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-ingress
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                IP=$(kubectl get ingress {{ include "thefirewall.fullname" . }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
                if [ ! -z "$IP" ]; then
                  echo "Ingress IP: $IP"
                  kubectl create configmap {{ include "thefirewall.fullname" . }}-ingress-config --from-literal=INGRESS_IP=$IP -o yaml --dry-run=client | kubectl apply -f -
                  break
                fi
                echo "Waiting for Ingress IP..."
                sleep 5
              done
      containers:
        - name: frontend
          env:
            - name: INGRESS_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "thefirewall.fullname" . }}-ingress-config
                  key: INGRESS_IP
            - name: VITE_API_BASE_URL
              value: "http://$(INGRESS_IP)"  # or https:// if using TLS
```

### Usage Instructions for Customers

1. Deploy the Helm chart:
```bash
helm install thefirewall ./helm-chart
```

2. The frontend will automatically wait for and use the Ingress IP.

3. To override the API URL manually (if needed):
```bash
helm install thefirewall ./helm-chart --set frontend.env.VITE_API_BASE_URL=http://your-custom-domain
```

### Testing Steps

1. Deploy the chart:
```bash
helm install thefirewall ./helm-chart
```

2. Watch the frontend pod status:
```bash
kubectl get pods -l app.kubernetes.io/component=frontend -w
```

3. Verify the environment variable:
```bash
kubectl exec -it $(kubectl get pod -l app.kubernetes.io/component=frontend -o jsonpath='{.items[0].metadata.name}') -- env | grep VITE_API_BASE_URL
```

### Notes
- The initContainer will retry until the Ingress IP is available
- Customers can still override VITE_API_BASE_URL using Helm values if needed
- This approach works for both HTTP and HTTPS (just change the protocol in the URL)
- Remember to update documentation to reflect these changes

### Security Considerations
- The ServiceAccount has minimal permissions (only Ingress read access)
- ConfigMap is namespaced and follows release naming conventions
